### ISSUE TITLE
checkpoint_url = "https://hanlab.mit.edu/files/course/labs/vgg.cifar.pretrained.pth" the link is not working

### ISSUE THREAD

**Issue by xihajun** [mit-han-lab/6s965-fall2022#75]
Many thanks for this lecture! It seems that the link for the pretrained model: `checkpoint_url = "https://hanlab.mit.edu/files/course/labs/vgg.cifar.pretrained.pth"` is not working anymore. I wonder if it is possible to fix that?

**Comment by zhijian-liu** [comment]
Could you please use https://file.hanlab.ai/courses/6s965/labs/assets/vgg.cifar.pretrained.pth instead?

**Comment by xihajun** [comment]
Thanks a lot!
